[package]
name = "fuzzysearch-owo"
version = "0.7.4"
edition = "2021"
authors = ["Syfaro <syfaro@huefox.com>"]
publish = false

[package.metadata.release]
allow-branch = ["main"]
sign-tag = true

[features]
env = ["dotenv"]

[dependencies]
tracing = "0.1"
anyhow = "1"
clap = { version = "3.0.0-rc.4", features = ["derive", "env", "cargo", "wrap_help"] }
dotenv = { version = "0.15", optional = true }
thiserror = "1"
prometheus = { version = "0.13", features = ["process"] }
lazy_static = "1"
async-trait = "0.1"

sentry = "0.25"
sentry-actix = "0.25"

opentelemetry = "0.17"
tracing-opentelemetry = "0.17"

uuid = { version = "0.8", features = ["v4", "serde"] }

futures = "0.3"
tokio = { version = "1", features = ["full"] }
tempfile = "3"
bytes = "1"

actix = "0.13"
actix-router = "0.5"
actix-web = "4"
actix-web-actors = "4"
actix-http = "3"
actix-multipart = "0.4"
tracing-actix-web = { version = "0.5", features = ["opentelemetry_0_17"] }
actix-session = { version = "0.6", features = ["cookie-session"] }
actix-files = "0.6"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }

askama = { version = "0.11", features = ["serde-json", "humansize"] }
argonautica = "0.2"
zxcvbn = "2"
sha2 = "0.10"
hex = "0.4"
image = "0.23"
rand = "0.8"

reqwest = { version = "0.11", features = ["json", "cookies"] }
scraper = "0.12"
regex = "1"

rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_s3 = "0.47"

redis = { version = "0.21", features = ["tokio-comp", "aio", "connection-manager"] }
redlock = { git = "https://github.com/Syfaro/redlock-rs.git" }
faktory = "0.11"

lettre = { version = "0.10.0-rc.4", features = ["tokio1-native-tls", "tracing", "serde"] }

oauth2 = { version = "4", features = ["reqwest"] }
hmac = "0.12"
md-5 = "0.10"

roux = "1"
radix_fmt = "1"
infer = "0.7"

furaffinity-rs = { git = "https://github.com/Syfaro/furaffinity-rs.git" }
fuzzysearch = { git = "https://github.com/Syfaro/fuzzysearch-rs.git", features = ["trace", "local_hash"] }
tgbotapi = { git = "https://github.com/Syfaro/tgbotapi-rs.git" }

fuzzysearch-common = { git = "https://github.com/Syfaro/fuzzysearch.git", features = ["queue"] }

[dependencies.sqlx]
version = "0.5"
features = [
    "runtime-tokio-native-tls",
    "postgres",
    "macros",
    "migrate",
    "uuid",
    "json",
    "offline",
    "chrono"
]
