jobs:
  - name: check f-list
    every: "*/5 * * * *"
    job_type: flist_gallery
    queue: fuzzysearch_owo_bulk
    args: []
    custom:
      initiator: schedule
  - name: check reddit
    every: "*/5 * * * *"
    job_type: reddit_check
    queue: fuzzysearch_owo_bulk
    args: []
    custom:
      initiator: schedule
  - name: collect deviantart
    every: "0 4 * * *"
    job_type: deviantart_accounts
    queue: fuzzysearch_owo_core
    args: []
    custom:
      initiator: schedule
  - name: create daily digests
    every: "0 6 * * *"
    job_type: create_email_digests
    queue: fuzzysearch_owo_core
    args: ["daily"]
    custom:
      initiator: schedule
  - name: create weekly digests
    every: "0 0 * * MON"
    job_type: create_email_digests
    queue: fuzzysearch_owo_core
    args: ["weekly"]
    custom:
      initiator: schedule
  - name: process pending deletes
    every: "0 * * * *"
    job_type: pending_deletion
    queue: fuzzysearch_owo_core
    custom:
      initiator: schedule
