jobs:
  - name: check f-list
    every: "*/5 * * * *"
    job_type: flist_gallery
    queue: fuzzysearch_owo_outgoing
    args: []
    custom:
      initiator: schedule
  - name: collect deviantart
    every: "0 4 * * *"
    job_type: deviantart_accounts
    queue: fuzzysearch_owo_outgoing
    args: []
    custom:
      initiator: schedule
