name: Docker Images

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  images:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Get stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move binary
        run: |
          mv target/release/fuzzysearch-owo fuzzysearch-owo

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: fuzzysearch-owo
          path: |
            fuzzysearch-owo

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/fuzzysearch-owo

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Remove old package versions
        uses: actions/delete-package-versions@v2
        with:
          package-name: "fuzzysearch-owo"
          min-versions-to-keep: 2
